name: Generate Snake 🐍

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia à meia-noite (UTC)
  workflow_dispatch:     # permite rodar manualmente pelo botão no GitHub

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Clona o repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Gera a cobrinha
      - name: Gerar cobrinha SVG
        uses: Platane/snk@v3
        with:
          github_user_name: brizadev
          outputs: |
            ./output/github-contribution-grid-snake.svg

      # Faz commit automático do SVG
      - name: Commit e Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "🐍 Atualizando cobrinha"
          add: "output/github-contribution-grid-snake.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
